---
- name: Testing Handlers
  hosts: all
  tasks:
  - block:
    - name: Install 7zip
      win_chocolatey:
        name: flashplayerpp
        state: present
    rescue: 
    - name: Install 7zip
      win_chocolatey:
        name: flashplayerpp
        state: absent
      notify:
      - reboot server
    always:
    - name: This is another task
      debug:
        msg: Final task
  handlers:
  - name: reboot server
    win_reboot: