---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install vlc
    win_chocolatey:
      name: vlc
      state: present
    ignore_errors: true
    notify:
    - reboot server
  - name: failing the tasks
    fail:
      msg: Failing the task as required
    ignore_errors: true
  handlers:
  - name: reboot server
    win_reboot: