---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install Dotnet4.6.1
    win_chocolatey:
      name: dotnet4.6.1
      state: present
    notify:
    - reboot server
  - name: failing the tasks
    fail:
      msg: Failing the task as required
  handlers:
  - name: reboot server
    win_reboot: