---
- name: Checking is the variables is defined
  hosts: all
  vars: 
    my_service: Web-Server
  tasks:
  - name: Install "{{my_service}}" with sub features and mgmt tools
    win_feature:
      name: "{{my_service}}"
      state: present
      include_sub_features: yes
      include_management_tools: yes
    when: my_service is defined